### ISSUE TITLE
Inlined functions in function level profiling

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/cairo-profiler#81]
Mapping from Scarb 
```toml
[cairo]
unstable-add-statements-functions-debug-info = true
```
are needed for this
